name: web_portfolio
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.2.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.2
  hooks_riverpod: ^3.0.3
  intl: ^0.20.2
  rive: ^0.14.0-dev.6
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  riverpod_lint: ^3.0.3
  url_launcher: ^6.3.2

dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.7.1
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/rive/
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/assets
  line_length: 80

  assets:
    enabled: true
    outputs:
      directory_path_enabled: true

flutter_native_splash:
  color: "#0E0D16"
  image: assets/images/logo.png
  web: true

